# Generated by Django 4.2.27 on 2026-01-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('call_sid', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=100)),
                ('call_status', models.CharField(max_length=32)),
                ('direction', models.CharField(blank=True, max_length=16, null=True)),
                ('from_number', models.CharField(blank=True, max_length=32, null=True)),
                ('to_number', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('correlation_sid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('error_code', models.CharField(blank=True, max_length=16, null=True)),
                ('severity', models.CharField(max_length=16)),
                ('product', models.CharField(blank=True, max_length=64, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('request_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
