# Generated by Django 6.0.1 on 2026-01-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_callevent_from_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callevent',
            name='account_sid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='errorevent',
            name='account_sid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
