# Generated by Django 6.0.1 on 2026-01-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_callevent_account_sid_errorevent_account_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorevent',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
