# Generated by Django 6.0.1 on 2026-02-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_errorevent_error_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callevent',
            old_name='raw_payload',
            new_name='meta_data',
        ),
        migrations.RenameField(
            model_name='errorevent',
            old_name='raw_payload',
            new_name='meta_data',
        ),
        migrations.RemoveField(
            model_name='callevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='callevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='errorevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='errorevent',
            name='http_status',
        ),
        migrations.RemoveField(
            model_name='errorevent',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='callevent',
            name='conference_sid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='call_sid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='call_status',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='direction',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='event_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='from_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='to_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
