# Generated by Django 6.0.1 on 2026-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_raw_payload_callevent_meta_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorevent',
            name='id',
        ),
        migrations.AlterField(
            model_name='callevent',
            name='account_sid',
            field=models.CharField(blank=True, db_index=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='call_sid',
            field=models.CharField(blank=True, db_index=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='conference_sid',
            field=models.CharField(blank=True, db_index=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='direction',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='event_id',
            field=models.CharField(max_length=34, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='from_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='to_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='account_sid',
            field=models.CharField(blank=True, db_index=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='correlation_sid',
            field=models.CharField(blank=True, db_index=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='error_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='event_id',
            field=models.CharField(max_length=34, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='request_sid',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='severity',
            field=models.CharField(max_length=7),
        ),
    ]
