# Generated by Django 6.0.1 on 2026-04-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_errorevent_id_alter_callevent_account_sid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='errorevent',
            options={},
        ),
    ]
